title = "Real Estate Photography |Higleys Drone Solutions | NEPA/ NY"
languageCode = "en-us"
copyright = "© Higley Drone Solutions"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Europe/Berlin"
timeout = 120
paginate = 8
baseURL = "https://realestate.higleysdrones.com/"

[params]
  title = "My Gallery"
  description = "Example site for hugo-theme-gallery"
  defaultTheme = "light"
  paginate = 8

[author]
  name = "Your Name"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[menu]
[[menu.footer]]
  name = "GitHub"
  url = "https://github.com/nicokaiser/hugo-theme-gallery/"
  weight = 3
